version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ai_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    env_file:
      - .env
    command: >
      bash -c "playwright install chromium && uvicorn main:app --host 0.0.0.0 --port 8000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: ai_frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
